1.13.0
AnacondaRecipes/onnx-feedstock pull request #7
Opened 2023-01-24 22:16 UTC by ELundby45

# onnx 1.13.0
upstream: https://github.com/onnx/onnx/tree/v1.13.0
`requirements.txt`: https://github.com/onnx/onnx/blob/v1.13.0/requirements.txt

## Changes
- Bump version and SHA
- Remove unnecessary `ignore_run_exports`
- Update dependencies

## Notes
- Adds python 3.11 support
- `abs.yaml` file to be removed before merging (or after https://github.com/AnacondaRecipes/protobuf-feedstock/pull/18)
- Linter complains of pinnings in host section. All deps w/o pinnings are in CBC or are python build tools

2023-01-24 22:41 UTC, cbouss requested changes

2023-01-24 22:41 UTC, cbouss commented on recipe/meta.yaml
> +    - libprotobuf 3.20.3
This shouldn't be pinned in that case, because we want to use the pinning specified in conda_build_config.yaml.

2023-01-30 22:30 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_75tcnct5bi/clone/recipe/meta.yaml:34: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
Errors were found

</details>

2023-01-30 23:05 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_0blkih9pan/clone/recipe/meta.yaml:34: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
Errors were found

</details>

2023-01-30 23:21 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_31nvcm2v38/clone/recipe/meta.yaml:32: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
Errors were found

</details>

2023-01-31 23:02 UTC, AndrewVallette approved these changes
LGTM!

2023-01-31 23:04 UTC, marcoesters reviewed
Do we need to pin protobuf and libprotobuf because of the bug?

The package that the linter is complaining about is protobuf. Even if you pinned protobuf to {{ libprotobuf }}, it would still do it because of a bug I'm working on.

2023-01-31 23:20 UTC, ELundby45 commented
> Do we need to pin protobuf and libprotobuf because of the bug?
> 
> The package that the linter is complaining about is protobuf. Even if you pinned protobuf to {{ libprotobuf }}, it would still do it because of a bug I'm working on.

https://github.com/AnacondaRecipes/aggregate/pull/247/files will need to be merged first. This will enable the correct pinnings. 

Problems are actually arising from the incorrect usage of `ignore_run_exports` and/or dependencies missing from host section that can lead to missing pinnings from cbc.

2023-02-01 14:50 UTC, skupr-anaconda approved these changes

2023-02-01 15:19 UTC, cbouss approved these changes
LGTM

2023-02-01 20:25 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_167vwsqaz2/clone/recipe/meta.yaml:32: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
Errors were found

</details>

2023-02-01 20:29 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_13_zr7c5gl/clone/recipe/meta.yaml:32: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
Errors were found

</details>

2023-02-01 20:43 UTC, merged

2023-02-01 20:44 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_0cdp3p5l5w/clone/recipe/meta.yaml:32: host_section_needs_exact_pinnings: Packages in host must have exact version pinnings, except python build tools.
Errors were found

</details>